/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EspaceEntrepriseRouteImport } from './routes/espace-entreprise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatureRouteImport } from './routes/candidature'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspaceEntrepriseIndexRouteImport } from './routes/espace-entreprise.index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceEntrepriseRoute = EspaceEntrepriseRouteImport.update({
  id: '/espace-entreprise',
  path: '/espace-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureRoute = CandidatureRouteImport.update({
  id: '/candidature',
  path: '/candidature',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceEntrepriseIndexRoute = EspaceEntrepriseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspaceEntrepriseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/candidature': typeof CandidatureRoute
  '/contact': typeof ContactRoute
  '/espace-entreprise': typeof EspaceEntrepriseRouteWithChildren
  '/services': typeof ServicesRoute
  '/espace-entreprise/': typeof EspaceEntrepriseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/candidature': typeof CandidatureRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/espace-entreprise': typeof EspaceEntrepriseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/candidature': typeof CandidatureRoute
  '/contact': typeof ContactRoute
  '/espace-entreprise': typeof EspaceEntrepriseRouteWithChildren
  '/services': typeof ServicesRoute
  '/espace-entreprise/': typeof EspaceEntrepriseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/candidature'
    | '/contact'
    | '/espace-entreprise'
    | '/services'
    | '/espace-entreprise/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/candidature'
    | '/contact'
    | '/services'
    | '/espace-entreprise'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/candidature'
    | '/contact'
    | '/espace-entreprise'
    | '/services'
    | '/espace-entreprise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CandidatureRoute: typeof CandidatureRoute
  ContactRoute: typeof ContactRoute
  EspaceEntrepriseRoute: typeof EspaceEntrepriseRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-entreprise': {
      id: '/espace-entreprise'
      path: '/espace-entreprise'
      fullPath: '/espace-entreprise'
      preLoaderRoute: typeof EspaceEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature': {
      id: '/candidature'
      path: '/candidature'
      fullPath: '/candidature'
      preLoaderRoute: typeof CandidatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-entreprise/': {
      id: '/espace-entreprise/'
      path: '/'
      fullPath: '/espace-entreprise/'
      preLoaderRoute: typeof EspaceEntrepriseIndexRouteImport
      parentRoute: typeof EspaceEntrepriseRoute
    }
  }
}

interface EspaceEntrepriseRouteChildren {
  EspaceEntrepriseIndexRoute: typeof EspaceEntrepriseIndexRoute
}

const EspaceEntrepriseRouteChildren: EspaceEntrepriseRouteChildren = {
  EspaceEntrepriseIndexRoute: EspaceEntrepriseIndexRoute,
}

const EspaceEntrepriseRouteWithChildren =
  EspaceEntrepriseRoute._addFileChildren(EspaceEntrepriseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CandidatureRoute: CandidatureRoute,
  ContactRoute: ContactRoute,
  EspaceEntrepriseRoute: EspaceEntrepriseRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
